#!/usr/bin/env bash
set -ea

# Add current scripts directory to the path
cd $(dirname $0)
PATH="${PATH}:$(pwd)"

DISK="/dev/vda"
FORMAT="ext4"
MNT="/mnt"
KERNEL="linux-lts"
PKG_INSTALL="sudo vim tree"
PKG_IGNORE="cryptsetup device-mapper diffutils ed jfsutils logrotate lvm2 man-db man-pages mdadm nano netctl pciutils pcmciautils s-nail usbutils vi"
#REPO="http://pacman-cache.nerdhouse.io/\$repo/os/\$arch http://archlinux.mirrors.uk2.net/\$repo/os/\$arch"
REPO="http://archlinux.mirrors.uk2.net/\$repo/os/\$arch"

LANG="en_GB.UTF-8"
LOCALE="$LANG UTF-8"
ZONEINFO="Europe/London"
PKG_EXTRA="bash-completion docker openssh tcpdump"

echo "Running command: '$@'"
[ $# -gt 0 ] && eval "$@"
